
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import localFont from "next/font/local";
import ContextProvider from "./context/UseContext";

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "blue chat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <ContextProvider>

          {children}
          <Toaster richColors closeButton />
        </ContextProvider>
      </body>
    </html>
  );
}

